services:
  - type: web
    name: valorant-shop-checker-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    autoDeploy: true
    envVars:
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: ALLOWED_ORIGINS
        sync: false
